learn.bbs.web/Controllers/AreaController.cs
using learn.bbs.bl;
using learn.bbs.dal.EfModel;
using learn.bbs.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace learn.bbs.web.Controllers
{
    public class AreaController : Controller
    {
        private AreaDO areaBO = new AreaDO();
        private static int _pageSize = 10;

        [HttpPost]
        public ActionResult Search(string area_name, byte? area_status,int pageIndex = 1)
        {
            throw new Exception("你4谁");

            //var model = areaBO.FindByCondition(area => area.area_name.Contains(area_name))
            //    .Where(a => a.area_status == area_status)
            //    .Take(_pageSize)
            //    .ToList();
            var model = areaBO.GetAllArea();
            if (!string.IsNullOrEmpty(area_name))
            {
                model = model.Where(area => area.area_name.Contains(area_name));
            }
            if (area_status != null)
            {
                model = model.Where(a => a.area_status == area_status);
            }
            model = model.OrderByDescending(a => a.create_time);

            return PartialView("_ListPartView", model.ToPagedList(pageIndex, _pageSize));
        }

        [Authorize(Users = "admin")]     
        public ActionResult GetAreasByPage(int pageIndex = 1)
        {
            var model = areaBO.GetAllArea()
                .OrderByDescending(a => a.last_modify_time)
                .ToPagedList(pageIndex, _pageSize);
            return View("List", model);
        }

        [Route("area/mine/{index:int?}")]
        public ActionResult GetMyAreasByPage(int index = 1)
        {
            var model = areaBO.GetAllArea()
                .OrderByDescending(a => a.last_modify_time)
                .Skip((index - 1) * _pageSize)
                .Take(_pageSize)
                .ToList();
            return View("MyAreaList", model);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AddAreaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var area = new bbs_area();
                area.area_uid = Guid.NewGuid();
                area.appraise_type = model.AppraiseType;
                area.area_name = model.AreaName;
                area.area_status = model.AreaStatus;
                area.area_url = model.AreaUrl;
                area.begin_time = model.BeginTime;
                area.end_time = model.EndTime;
                area.creator = this.User.Identity.Name;
                area.create_time = DateTime.Now;
                area.last_modify_time = DateTime.Now;
                area.is_allow_reply = (byte)(model.IsAllowReply ? 1 : 0);
                area.post_count = 0;
                area.remark = model.Remark;
                areaBO.Add(area);
            }

            return RedirectToAction("GetAreasByPage", new { pageIndex = 1 });
        }

        public ActionResult Edit(Guid areaUid)
        {
            var entity = areaBO.FindByCondition(a=>a.area_uid == areaUid).First();
            var vm = new EditAreaViewModel();
            vm.AreaUid = entity.area_uid;
            vm.AreaName = entity.area_name;
            vm.AppraiseType = entity.appraise_type;
            vm.AreaStatus = entity.area_status;
            vm.AreaUrl = entity.area_url;
            vm.BeginTime = entity.begin_time;
            vm.EndTime = entity.end_time;
            vm.IsAllowReply = entity.is_allow_reply == 1;
            vm.Remark = entity.remark;
            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(EditAreaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var area = new bbs_area();
                area.area_uid = model.AreaUid;
                area.appraise_type = model.AppraiseType;
                area.area_name = model.AreaName;
                area.area_status = model.AreaStatus;
                area.area_url = model.AreaUrl;
                area.begin_time = model.BeginTime;
                area.end_time = model.EndTime;
                area.creator = this.User.Identity.Name;
                area.create_time = DateTime.Now;
                area.last_modify_time = DateTime.Now;
                area.is_allow_reply = (byte)(model.IsAllowReply ? 1 : 2);
                area.post_count = 0;
                area.remark = model.Remark;
                areaBO.Edit(area);
            }

            return RedirectToAction("GetAreasByPage", new { pageIndex = 1 });
        }

        [HttpPost]
        public void Delete(string[] areaUids)
        {
            foreach (string item in areaUids)
            {
                var areaUid = Guid.Parse(item);
                areaBO.Delete(areaUid);
            }
        }
    }
}

learn.bbs.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

learn.bbs.web/Views/Shared/_LayoutBBS.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
</head>
<body>
    <div style="overflow:hidden">
        <div id="div_weather" class="text-center" style="float:left;padding:14px 20px">

        </div>
        <div style="float:left">
            <img style="height:50px;width:50px" src="~/Images/logo.png" /><span style="font-size:18px;font-weight:bold">learn.com</span>
        </div>
        <div style="float:right;padding-top:10px;padding-right:140px;">
            <span style="font-size:14px;font-weight:bold">@this.User.Identity.Name</span>
            <a class="" href="/Account/SignOut">退出</a>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding-left:140px">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/home/index">首页</a></li>
                    <li><a href="/area/mine">我的贴吧</a></li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">关于</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">后台管理 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li> <a href="@Url.Action("GetAreasByPage", "Area")"> 贴吧管理 </a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <header></header>
    <div class="container" style="">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    <hr />
    <footer class="footer" style="background-color:#fff">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-lg-offset-4"><p>&copy; @DateTime.Now.Year - learn.com</p></div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $.ajax({
                type: "get",
                url: "/home/GetWeather",
                data: "",
                dataType: "json",
                success: function (data) {
                    debugger;
                    data = JSON.parse(data);
                    var city = data.results[0].location.name;
                    var text = data.results[0].now.text;
                    var temperature = data.results[0].now.temperature;
                    $("#div_weather").html(city + ": " + text + "&nbsp;" + temperature + "&#8451;");
                }
            });
        });


    </script>
    
    @*<script type="text/javascript" src="https://api.seniverse.com/v3/weather/now.json?location=深圳&ts=1443079775&ttl=30&uid=U0995D22B0&sig=[your_signature]&callback=showWeather"></script>*@
    <script type="text/javascript">
        function showWeather(data) {
            var city = data.results[0].location.name;
            var text = data.results[0].now.text;
            var temperature = data.results[0].now.temperature;
            alert(city + text + temperature);
        }
    </script>
</body>
</html>